import { CServerMain } from "../../artgine/network/CServerMain.js";
import { CFileServer } from "../../artgine/server/CFileServer.js";
import { COAuthServer } from "../../artgine/server/COAuthServer.js";
import { CTerminalRouter } from "../../artgine/server/CTerminalRouter.js";
import { CAIChatRouter } from "../../artgine/server/CAIChatRouter.js";
import { CPlaywrightRouter } from "../../artgine/server/CPlaywrightRouter.js";
new CFileServer().SetServerMain(CServerMain.Main());
new COAuthServer().SetServerMain(CServerMain.Main());
new CTerminalRouter().SetServerMain(CServerMain.Main());
new CAIChatRouter().SetServerMain(CServerMain.Main());
new CPlaywrightRouter().SetServerMain(CServerMain.Main());
