import { CServerMain } from "../../artgine/network/CServerMain.js";
import { CBoardServer } from "../../artgine/server/CBoardServer.js";
import { CFileServer } from "../../artgine/server/CFileServer.js";
import { COAuthServer } from "../../artgine/server/COAuthServer.js";
import { CSingServer } from "../../artgine/server/CSingServer.js";
import { CTerminalRouter } from "../../artgine/server/CTerminalRouter.js";
import { CDownloadServer } from "../../artgine/server/CDownloadServer.js";
import { CAIChatRouter } from "../../artgine/server/CAIChatRouter.js";
import { CPlaywrightRouter } from "../../artgine/server/CPlaywrightRouter.js";
import { CRemoteDesktopRouter } from "../../artgine/server/CRemoteDesktopRouter.js";
import { CMemoRouter } from "../../artgine/server/CMemoRouter.js";
new CSingServer().SetServerMain(CServerMain.Main());
new COAuthServer().SetServerMain(CServerMain.Main());
new CBoardServer().SetServerMain(CServerMain.Main());
new CDownloadServer().SetServerMain(CServerMain.Main());
new CFileServer().SetServerMain(CServerMain.Main());
new CTerminalRouter().SetServerMain(CServerMain.Main());
new CAIChatRouter().SetServerMain(CServerMain.Main());
new CPlaywrightRouter().SetServerMain(CServerMain.Main());
new CRemoteDesktopRouter().SetServerMain(CServerMain.Main());
new CMemoRouter().SetServerMain(CServerMain.Main());
