import { CServerMain } from "../../Artgine/artgine/network/CServerMain.js";
import { CFileServer } from "../../Artgine/artgine/server/CFileServer.js";
import { CTerminalRouter } from "../../Artgine/artgine/server/CTerminalRouter.js";
import { CAIChatRouter } from "../../Artgine/artgine/server/CAIChatRouter.js";
import { CPlaywrightRouter } from "../../Artgine/artgine/server/CPlaywrightRouter.js";
import { CRemoteDesktopRouter } from "../../Artgine/artgine/server/CRemoteDesktopRouter.js";
import { CMemoRouter } from "../../Artgine/artgine/server/CMemoRouter.js";
new CFileServer().SetServerMain(CServerMain.Main());
new CTerminalRouter().SetServerMain(CServerMain.Main());
new CAIChatRouter().SetServerMain(CServerMain.Main());
new CPlaywrightRouter().SetServerMain(CServerMain.Main());
new CRemoteDesktopRouter().SetServerMain(CServerMain.Main());
new CMemoRouter().SetServerMain(CServerMain.Main());
